IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Statuses')
BEGIN
    CREATE TABLE dbo.Statuses 
    (
        Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        Name NVARCHAR(255) UNIQUE NOT NULL,
		CONSTRAINT PK_Statuses_Id PRIMARY KEY CLUSTERED (Id ASC),
        INDEX IX_Statuses (Name)
    )
END