IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Contacts')
BEGIN
    CREATE TABLE dbo.Contacts 
    (
        Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        Name NVARCHAR(255) NOT NULL,
        Surname NVARCHAR(500) NOT NULL,
        EmailAddress NVARCHAR(500) UNIQUE NOT NULL,
        CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
        DeletedAt DATETIME DEFAULT NULL,
		CONSTRAINT PK_Contacts PRIMARY KEY CLUSTERED (Id ASC),
        INDEX IX_Contacts (Name, CreatedAt, DeletedAt, EmailAddress)
    )
END