IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Contacts')
BEGIN
    CREATE TABLE dbo.Contacts 
    (
        Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        Name NVARCHAR(255) NOT NULL,
        Surname NVARCHAR(500) NOT NULL,
        EmailAddress NVARCHAR(500) UNIQUE NOT NULL,
		CONSTRAINT PK_Contacts PRIMARY KEY CLUSTERED (Id ASC, EmailAddress ASC),
        INDEX IX_Contacts (Name)
    )
END